defaults: &defaults
  docker:
    - image: cypress/browsers:chrome64
  working_directory: ~/web-components-to-react

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create package-lock.json checksum
          command: sha256sum package-lock.json > .package-lock-sum
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum ".package-lock-sum" }}
      - run:
          name: Install
          command: CYPRESS_INSTALL_BINARY=0 npm install
      - run:
          name: Prepare
          command: npm run prepare
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum ".package-lock-sum" }}
      - save_cache:
          paths:
            - ~/web-components-to-react
          key: v1-repo-{{ .Revision }}
  lint:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - run:
          name: Lint
          command: npm run lint
  buildDemo:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - run:
          name: Build stencil
          command: $(npm bin)/stencil build
      - save_cache:
          paths:
            - demo/static
          key: v1-demo-build-{{ .Revision }}
  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
          - v1-demo-build-{{ .Revision }}
      - run:
          name: Install Cypress
          command: $(npm bin)/cypress install
      - run:
          name: Test
          command: ./scripts/runCypressCi.sh

workflows:
  version: 2
  deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - buildDemo:
          requires:
            - install
      - test:
          requires:
            - buildDemo
